 server:
   port: 8081
   servlet:
     context-path: '/physio-node'
 spring:
   jpa:
     show-sql: true
     hibernate:
       ddl-auto: validate
   datasource:
     url: 'jdbc:mysql://localhost:3306/physio_node'
     username: 'root'
   flyway:
    enabled: true

 logging:
   level:
     org.springframework: DEBUG
